Client/Controllers/CarController.cs
using Client.Interfaces;
using Client.Models;
using Client.Models.CarViewModel;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Shared.Models;
using Shared.Requests;
using Shared.Responses;
using System;
using System.Linq;
using System.Threading.Tasks;

namespace Client.Controllers
{

    [Route("[controller]")]
    [Controller]
    public class CarController : Controller
    {
        readonly SignInManager<ApplicationUser> _signInManager;
        readonly IClientMessageHub _serverMessageHub;

        public CarController(SignInManager<ApplicationUser> signInManager, IClientMessageHub serverMessageHub)
        {
            _signInManager = signInManager;
            _serverMessageHub = serverMessageHub;
        }


        [HttpGet("index")]
        public async Task<IActionResult> Index(Guid? id)
        {
            if (!_signInManager.IsSignedIn(User))
                return RedirectToAction("Index", "Home");

            var correlationId = Guid.NewGuid();
            await _serverMessageHub.SendToServerMessage(new GetCarsRequest(), correlationId);
            var getCarsResponse = await _serverMessageHub.ReceiveFromServerMessage<GetCarsResponse>(correlationId);

            correlationId = Guid.NewGuid();
            await _serverMessageHub.SendToServerMessage(new GetCompaniesRequest(), correlationId);
            var getCompaniesResponse = await _serverMessageHub.ReceiveFromServerMessage<GetCompaniesResponse>(correlationId);

            var selectedCompany = id == null
                ? getCompaniesResponse.Companies.FirstOrDefault()
                : getCompaniesResponse.Companies.SingleOrDefault(c => c.Id == id);

            var companyId = selectedCompany?.Id ?? Guid.NewGuid();
            getCarsResponse.Cars = getCarsResponse.Cars.Where(c => c.CompanyId == companyId).ToList();

            var selectList = getCompaniesResponse.Companies.Select(c => new SelectListItem
            {
                Text = c.Name,
                Value = c.Id.ToString(),
                Selected = c.Id == companyId
            }).ToList();

            var viewModel = new CarListViewModel(companyId)
            {
                CompanySelectList = selectList,
                Cars = getCarsResponse.Cars
            };

            ViewBag.CompanyId = companyId;
            ViewBag.CompanyName = selectedCompany?.Name;

            return View(viewModel);
        }

        [HttpGet("details")]
        public async Task<IActionResult> Details(Guid id)
        {
            var correlationId = Guid.NewGuid();
            await _serverMessageHub.SendToServerMessage(new GetCarRequest(id), correlationId);
            var getCarResponse = await _serverMessageHub.ReceiveFromServerMessage<GetCarResponse>(correlationId);

            correlationId = Guid.NewGuid();
            await _serverMessageHub.SendToServerMessage(new GetCompanyRequest(getCarResponse.Car.CompanyId), correlationId);
            var getCompanyResponse = await _serverMessageHub.ReceiveFromServerMessage<GetCompanyResponse>(correlationId);

            ViewBag.CompanyName = getCompanyResponse.Company.Name;
            return View(getCarResponse.Car);
        }

        [HttpGet("create")]
        public async Task<IActionResult> Create(string id)
        {
            var companyId = new Guid(id);
            var car = new Car(companyId);

            var correlationId = Guid.NewGuid();
            await _serverMessageHub.SendToServerMessage(new GetCompanyRequest(companyId), correlationId);
            var getCompanyResponse = await _serverMessageHub.ReceiveFromServerMessage<GetCompanyResponse>(correlationId);

            ViewBag.CompanyName = getCompanyResponse.Company.Name;
            return View(car);
        }

        // POST: Car/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost("create")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(
                [Bind("CompanyId,VIN,RegNr,Online")] Car car)
        {
            if (!ModelState.IsValid) return View(car);

            car.Id = Guid.NewGuid();
            var correlationId = Guid.NewGuid();
            await _serverMessageHub.SendToServerMessage(new CreateCarRequest(car), correlationId);
            var createCarResponse = await _serverMessageHub.ReceiveFromServerMessage<CreateCarResponse>(correlationId);

            return RedirectToAction("Index", new { id = car.CompanyId });
        }

        [HttpGet("edit")]
        public async Task<IActionResult> Edit(Guid id)
        {
            var correlationId = Guid.NewGuid();
            await _serverMessageHub.SendToServerMessage(new GetCarRequest(id), correlationId);
            var getCarResponse = await _serverMessageHub.ReceiveFromServerMessage<GetCarResponse>(correlationId);

            getCarResponse.Car.Disabled = true; //Prevent updates of Online/Offline while editing
            correlationId = Guid.NewGuid();
            await _serverMessageHub.SendToServerMessage(new UpdateCarRequest(getCarResponse.Car), correlationId);
            var updateCarResponse = await _serverMessageHub.ReceiveFromServerMessage<UpdateCarResponse>(correlationId);

            correlationId = Guid.NewGuid();
            await _serverMessageHub.SendToServerMessage(new GetCompanyRequest(getCarResponse.Car.CompanyId), correlationId);
            var getCompanyResponse = await _serverMessageHub.ReceiveFromServerMessage<GetCompanyResponse>(correlationId);

            ViewBag.CompanyName = getCompanyResponse.Company.Name;

            return View(getCarResponse.Car);
        }

        // POST: Car/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost("edit")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Guid id, [Bind("Id, Online")] Car car)
        {
            if (!ModelState.IsValid) return View(car);

            var correlationId = Guid.NewGuid();
            await _serverMessageHub.SendToServerMessage(new GetCarRequest(id), correlationId);
            var oldCarResponse = await _serverMessageHub.ReceiveFromServerMessage<GetCarResponse>(correlationId);


            var oldCar = oldCarResponse.Car;
            oldCar.Online = car.Online;
            oldCar.Disabled = false; //Enable updates of Online/Offline when editing done

            correlationId = Guid.NewGuid();
            await _serverMessageHub.SendToServerMessage(new UpdateCarRequest(oldCar), correlationId);
            var updateCarResponse = await _serverMessageHub.ReceiveFromServerMessage<UpdateCarResponse>(correlationId);

            return RedirectToAction("Index", new { id = oldCar.CompanyId });
        }

        [HttpGet("delete")]
        public async Task<IActionResult> Delete(Guid id)
        {
            var correlationId = Guid.NewGuid();
            await _serverMessageHub.SendToServerMessage(new GetCarRequest(id), correlationId);
            var getCarResponse = await _serverMessageHub.ReceiveFromServerMessage<GetCarResponse>(correlationId);

            return View(getCarResponse.Car);
        }

        // POST: Car/Delete/5
        [HttpPost("delete")]
        [ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(Guid id)
        {
            var correlationId = Guid.NewGuid();
            await _serverMessageHub.SendToServerMessage(new GetCarRequest(id), correlationId);
            var getCarResponse = await _serverMessageHub.ReceiveFromServerMessage<GetCarResponse>(correlationId);


            correlationId = Guid.NewGuid();
            await _serverMessageHub.SendToServerMessage(new DeleteCarRequest(id), correlationId);
            var deleteCarResponse = await _serverMessageHub.ReceiveFromServerMessage<DeleteCarResponse>(correlationId);

            return RedirectToAction("Index", new { id = getCarResponse.Car.CompanyId });
        }

        [HttpGet("regnravailableasync")]
        public async Task<JsonResult> RegNrAvailableAsync(string regNr)
        {
            var correlationId = Guid.NewGuid();
            await _serverMessageHub.SendToServerMessage(new GetCarsRequest(), correlationId);
            var getCarsResponse = await _serverMessageHub.ReceiveFromServerMessage<GetCarsResponse>(correlationId);

            bool isAvailable = getCarsResponse.Cars.All(c => c.RegNr != regNr);

            return Json(isAvailable);
        }

        [HttpGet("vinavailableasync")]
        public async Task<JsonResult> VinAvailableAsync(string vin)
        {
            var correlationId = Guid.NewGuid();
            await _serverMessageHub.SendToServerMessage(new GetCarsRequest(), correlationId);
            var getCarsResponse = await _serverMessageHub.ReceiveFromServerMessage<GetCarsResponse>(correlationId);

            bool isAvailable = getCarsResponse.Cars.All(c => c.VIN != vin);

            return Json(isAvailable);
        }
    }
}

Client/Controllers/CompanyController.cs
using Client.Interfaces;
using Client.Models;
using Client.Models.CompanyViewModel;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Shared.Models;
using Shared.Requests;
using Shared.Responses;
using System;
using System.Linq;
using System.Threading.Tasks;

namespace CarClient.Controllers
{

    [Route("[controller]")]
    [Controller]
    public class CompanyController : Controller
    {
        readonly SignInManager<ApplicationUser> _signInManager;
        readonly IClientMessageHub _serverMessageHub;

        public CompanyController(SignInManager<ApplicationUser> signInManager, IClientMessageHub serverMessageHub)
        {
            _signInManager = signInManager;
            _serverMessageHub = serverMessageHub;
        }


        [HttpGet("/company")]

        public async Task<IActionResult> Index()
        {
            if (!_signInManager.IsSignedIn(User)) return RedirectToAction("Index", "Home");

            var correlationId = Guid.NewGuid();
            await _serverMessageHub.SendToServerMessage(new GetCompaniesRequest(), correlationId);
            var getCompaniesResponse = await _serverMessageHub.ReceiveFromServerMessage<GetCompaniesResponse>(correlationId);

            var companies = getCompaniesResponse.Companies;

            foreach (var company in companies)
            {
                correlationId = Guid.NewGuid();
                await _serverMessageHub.SendToServerMessage(new GetCarsRequest(), correlationId);
                var getCarsResponse = await _serverMessageHub.ReceiveFromServerMessage<GetCarsResponse>(correlationId);

                var cars = getCarsResponse.Cars;
                cars = cars.Where(c => c.CompanyId == company.Id).ToList();
                company.Cars = cars;
            }

            var companyViewModel = new CompanyViewModel { Companies = companies };

            return View(companyViewModel);
        }


        [HttpGet("/company/details")]
        public async Task<IActionResult> Details(Guid id)
        {
            var correlationId = Guid.NewGuid();
            await _serverMessageHub.SendToServerMessage(new GetCompanyRequest(id), correlationId);
            var getCompanyResponse = await _serverMessageHub.ReceiveFromServerMessage<GetCompanyResponse>(correlationId);

            var company = getCompanyResponse.Company;

            return View(company);
        }

        [HttpGet("/company/create")]
        public IActionResult Create()
        {
            return View();
        }

        // POST: Company/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost("/company/create")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Name,Address,CreationTime")] Company company)
        {
            if (!ModelState.IsValid) return View(company);
            company.Id = Guid.NewGuid();

            var correlationId = Guid.NewGuid();
            await _serverMessageHub.SendToServerMessage(new CreateCompanyRequest(company), correlationId);
            var creteCompanyResponse = await _serverMessageHub.ReceiveFromServerMessage<CreateCompanyResponse>(correlationId);

            return RedirectToAction(nameof(Index));
        }

        [HttpGet("/company/edit")]
        public async Task<IActionResult> Edit(Guid id)
        {
            var correlationId = Guid.NewGuid();
            await _serverMessageHub.SendToServerMessage(new GetCompanyRequest(id), correlationId);
            var getCompanyResponse = await _serverMessageHub.ReceiveFromServerMessage<GetCompanyResponse>(correlationId);

            var company = getCompanyResponse.Company;

            return View(company);
        }

        // POST: Company/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost("/company/edit")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Guid id, [Bind("Id,CreationTime, Name, Address")] Company company)
        {
            if (!ModelState.IsValid) return View(company);

            var correlationId = Guid.NewGuid();
            await _serverMessageHub.SendToServerMessage(new GetCompanyRequest(id), correlationId);
            var getCompanyResponse = await _serverMessageHub.ReceiveFromServerMessage<GetCompanyResponse>(correlationId);

            var oldCompany = getCompanyResponse.Company;

            oldCompany.Name = company.Name;
            oldCompany.Address = company.Address;

            correlationId = Guid.NewGuid();
            await _serverMessageHub.SendToServerMessage(new UpdateCompanyRequest(company), correlationId);
            var updateCompanyResponse = await _serverMessageHub.ReceiveFromServerMessage<UpdateCompanyResponse>(correlationId);

            return RedirectToAction(nameof(Index));
        }

        [HttpGet("/company/delete")]
        public async Task<IActionResult> Delete(Guid id)
        {
            var correlationId = Guid.NewGuid();
            await _serverMessageHub.SendToServerMessage(new GetCompanyRequest(id), correlationId);
            var getCompanyResponse = await _serverMessageHub.ReceiveFromServerMessage<GetCompanyResponse>(correlationId);

            var company = getCompanyResponse.Company;

            return View(company);
        }

        // POST: Company/Delete/5
        [HttpPost("/company/delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(Guid id)
        {
            var correlationId = Guid.NewGuid();
            await _serverMessageHub.SendToServerMessage(new DeleteCompanyRequest(id), correlationId);
            var deleteCompanyResponse = await _serverMessageHub.ReceiveFromServerMessage<DeleteCompanyResponse>(correlationId);

            return RedirectToAction(nameof(Index));
        }
    }
}

Client/Views/Shared/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

Client/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
@{
    var nc = TempData["Nonce"];
}
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"]</title>
    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" nonce="@nc"/>
        <link rel="stylesheet" href="~/css/site.css" nonce="@nc" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" nonce="@nc" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" nonce="@nc" />
    </environment>
</head>
<body>
<nav class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li>
                    <a asp-area="" asp-controller="Home" asp-action="Index">All Vehicles</a>
                </li>
                @inject SignInManager<ApplicationUser> SignInManager
                @inject UserManager<ApplicationUser> UserManager
                @if (SignInManager.IsSignedIn(User))
                {
                    <li>
                        <a asp-area="" asp-controller="Company" asp-action="Index">Companies</a>
                    </li>
                    <li>
                        <a asp-area="" asp-controller="Car" asp-action="Index">Company Vehicles</a>
                    </li>}
            </ul>
            @await Html.PartialAsync("_LoginPartial")
        </div>
    </div>
</nav>
<div class="container body-content">
    @RenderBody()
    <hr/>
    <footer>
        <p>&copy; 2024 - Company Vehicles</p>
    </footer>
</div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js" nonce="@nc"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js" nonce="@nc"></script>
        <script src="~/js/site.js" asp-append-version="true" nonce="@nc"></script>
</environment>
<environment exclude="Development">
    <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
            asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
            asp-fallback-test="window.jQuery"
            crossorigin="anonymous"
            integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk" nonce="@nc">
    </script>
    <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
            asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
            asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
            crossorigin="anonymous"
            integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" nonce="@nc">
    </script>
     <script src="~/js/site.min.js" asp-append-version="true" nonce="@nc"></script>
</environment>

@RenderSection("Scripts", false)
</body>
</html>

Client/Views/Shared/_Spinner.cshtml
<!-- _Spinner.cshtml -->
@{
    var nc = TempData["Nonce"];
}
<div>
    <svg viewBox="0 0 800 800" xmlns="http://www.w3.org/2000/svg" width="100" height="100">
        <style  nonc="@nc">
            @@keyframes spin {
                to {
                    transform: rotate(360deg);
                }
            }

            @@keyframes spin2 {
                0% {
                    stroke-dasharray: 1, 800;
                    stroke-dashoffset: 0;
                }
                50% {
                    stroke-dasharray: 400, 400;
                    stroke-dashoffset: -200px;
                }
                100% {
                    stroke-dasharray: 800, 1;
                    stroke-dashoffset: -800px;
                }
            }

            .spin2 {
                transform-origin: center;
                animation: spin2 1.5s ease-in-out infinite,
                spin 2s linear infinite;
                animation-direction: alternate;
            }
        </style>
        <circle class="spin2" cx="400" cy="400" fill="none"
            r="200" stroke-width="50" stroke="#E387FF"
            stroke-dasharray="700 1400"
            stroke-linecap="round" />
    </svg>
</div>